dist: trusty
language: c++
install:
  - pip install --user -r requirements.txt

env:
  global:
    - PYTHON_VERSION="2.7"

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - liblapack-dev
      - libgmp3-dev
      - libsuitesparse-dev
      - libeigen3-dev
      
before_script:
  - export PYTHON_VERSION="2.7"
  - export CXX="g++-4.8" CC="gcc-4.8" FC="gfortran-4.8"
  - pushd ..
  - export INSTALL_ROOT=$PWD/install
  - git clone https://github.com/Statoil/libecl.git
  - git clone https://github.com/OPM/opm-parser.git
  - git clone https://github.com/pybind/pybind11.git
  - mkdir libecl/build
  - pushd libecl/build
  - cmake -DBUILD_PYTHON=OFF -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT ..
  - make install
  - popd
  - mkdir opm-parser/build
  - pushd opm-parser/build
  - git checkout release/2017.10/final
  - cmake -DCMAKE_PREFIX_PATH=$INSTALL_ROOT -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON ..
  - make install
  - popd
  - mkdir pybind11/build
  - pushd pybind11/build
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT ..
  - make install
  - popd
  - popd
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_PREFIX_PATH=$INSTALL_ROOT -DUSE_RPATH=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT ..
  - make install
  - export PYTHONPATH=$PYTHONPATH:$INSTALL_ROOT/lib/python${PYTHON_VERSION}/site-packages
  - ctest --output-on-failure
